### ISSUE TITLE
Result

### ISSUE THREAD

**Issue by Abishevs** [Abishevs/gymarbete#11]
Gsr inkludera 7-10 iteration, andra är värdelössa (icke random)
Inkludera Fixed 7-10 (för jämförelse till gsr)
SOC första är värdeloss
SOC run 2 (relativt stort värde men inom ramen)
SOC 3-10 inom ramen ( ser bra ut, har väldigt nära chi två resulat) 
SOC 3 & 4 nära 10 (icke så bra?). SOC 5 & 7 (minsta). SOC 6 & 8 väldigt nära och relativt höga värdena. SOC 3 & 4 likadant mönster som 9 & 10. ( Mer iterationer??).

**Comment by LeoAllStar** [comment]
Suffle chi-square test 1-15 shuflles

significant:
All fixed riffles are significant as expected.
All GSR riffles under 7 shufles are siginficant whitch is unsuprising, GSR with 9 shuffles is also siginficant, could be chalked up to chance.
Six pile shuffle with 1 and 2 shuffles are siginficant, makes sense since they are the lowest, six pile shuffle with 15 shuffles is also signinfcant which is likely just due to chance.
SOC pile shuffle with just 1 shuffle is significant a logical result bearing in mind its low shuffle amount, soc pile shuffle 3 and 10 shuffles are siginficant likely just by chance.
Ten pile shuffle with 1 and 15  shuffles were significant.
Wheel spiny no shuffles are siginficant

non siginficant:
No fixed riffles are non siginficant which is to be expecetd.
With the exeption of the 9 shullfe one all GSR riffles with above 7 shuffles are non signinficant, 11 shuflles was very close to being siginficant, all the other ones had p values under 10, 15 being the one with the lowest p value.
Six pile shuffles 3-14 are non siginficant, shuflles 3, 5, 8, 13, 14 are the only one with a pvalue above 10, 13 was the highets and 10 was the lowest.
SOC pile shuffle with shuffles 2 (Very weird potencial statistical anomaly), 4-9 and 11-15 are non siginficant, suffles 5, 6, 8 are the only ones with a p value above 10, highest was 8 and lowest was 15.
Ten pile shuffle 2-15 were non signinicant, 7, 11 and 13-15 had p value above 10, 7 was the highest and 3 was the lowest.
Wheel spiny all shuffles are non siginficant, shuflles 1, 2, 8, 9, 12 and 15 are the shuffle with p vaue above 10, with shuffle with the highest p value was 2 and lowest was 13.

**Comment by Abishevs** [comment]
Det simulerades 75 kortleken med iterationer varierade från 1-15. chi-square-testet visade signifikanta resultatet för följande algoritmer och iterationer <visa grafen och chi square värdena>. 

Icke signifikanta resultatet ifrån chi-square-testet visade sig följande algoritmer <visa grafer och p-värdena> (visa dem vilka grafer visar en förändring eller en stor förändring i p-värdet, **fokusera på minsta möjliga iterationer och bortse från icke relevanta resultat**)

FIgures to include in signficant and (Enorma värdena från chi-square-testet finns det ens poäng att ha med dem?)
GSR -1  (Apendix)
GSR-3 (Appendix)
GSR-6  (Appendix)

Pile SHuffles all first iterations are signficant (Too little movement of cards)
All 1 iterations add in (Appendix)

Pile shuffle with 6 bins:
Figure 2:  X^2: p-value: is one before an Non signfiicant value (Appendix)

Pile Shuffle (SOC) with 8 bins:
Figure 3 First and last card has slight devation in mean value NOT IDEAL for card shuffler (Appendix)
 X^2: p-value:
Pile shuffle with 10 bins:
15 but no point of having it (Tooo many iterations)
 X^2: p-value:

Inte signifikant figures.
GSR-7 X^2: p-value:
GSR-11  X^2: p-value:

Which is the best and why? 
-
